name: CD:- Release Extension

on:
  push:
    branches: [main]

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node Dependencies
        run: npm ci
      - name: Generate Semantic Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
      - name: Generate Gitmoji Changelog
        run: npx gitmoji-changelog

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":pencil2: docs: update changelog [skip ci]"
